(cl:defpackage v2x_msgs-msg
  (:use )
  (:export
   "<PARTICIPANTINFO>"
   "PARTICIPANTINFO"
   "<TRAFFICLIGHTINFO>"
   "TRAFFICLIGHTINFO"
   "<V2XSIGNALHMI>"
   "V2XSIGNALHMI"
   "<V2XSIGNALPLAN>"
   "V2XSIGNALPLAN"
  ))

