// Generated by gencpp from file diag_msgs/HeartBeatInfo.msg
// DO NOT EDIT!


#ifndef DIAG_MSGS_MESSAGE_HEARTBEATINFO_H
#define DIAG_MSGS_MESSAGE_HEARTBEATINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diag_msgs
{
template <class ContainerAllocator>
struct HeartBeatInfo_
{
  typedef HeartBeatInfo_<ContainerAllocator> Type;

  HeartBeatInfo_()
    : module_name()
    , rate(0)
    , timestamp(0.0)  {
    }
  HeartBeatInfo_(const ContainerAllocator& _alloc)
    : module_name(_alloc)
    , rate(0)
    , timestamp(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _module_name_type;
  _module_name_type module_name;

   typedef int8_t _rate_type;
  _rate_type rate;

   typedef double _timestamp_type;
  _timestamp_type timestamp;





  typedef boost::shared_ptr< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> const> ConstPtr;

}; // struct HeartBeatInfo_

typedef ::diag_msgs::HeartBeatInfo_<std::allocator<void> > HeartBeatInfo;

typedef boost::shared_ptr< ::diag_msgs::HeartBeatInfo > HeartBeatInfoPtr;
typedef boost::shared_ptr< ::diag_msgs::HeartBeatInfo const> HeartBeatInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diag_msgs::HeartBeatInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diag_msgs::HeartBeatInfo_<ContainerAllocator1> & lhs, const ::diag_msgs::HeartBeatInfo_<ContainerAllocator2> & rhs)
{
  return lhs.module_name == rhs.module_name &&
    lhs.rate == rhs.rate &&
    lhs.timestamp == rhs.timestamp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diag_msgs::HeartBeatInfo_<ContainerAllocator1> & lhs, const ::diag_msgs::HeartBeatInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diag_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "379e4ca949e84dbce581a0fc94145af7";
  }

  static const char* value(const ::diag_msgs::HeartBeatInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x379e4ca949e84dbcULL;
  static const uint64_t static_value2 = 0xe581a0fc94145af7ULL;
};

template<class ContainerAllocator>
struct DataType< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diag_msgs/HeartBeatInfo";
  }

  static const char* value(const ::diag_msgs::HeartBeatInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string module_name\n"
"int8 rate\n"
"float64 timestamp\n"
;
  }

  static const char* value(const ::diag_msgs::HeartBeatInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.module_name);
      stream.next(m.rate);
      stream.next(m.timestamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeartBeatInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diag_msgs::HeartBeatInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diag_msgs::HeartBeatInfo_<ContainerAllocator>& v)
  {
    s << indent << "module_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.module_name);
    s << indent << "rate: ";
    Printer<int8_t>::stream(s, indent + "  ", v.rate);
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIAG_MSGS_MESSAGE_HEARTBEATINFO_H
