// Generated by gencpp from file diag_msgs/VehicleAutoFunction.msg
// DO NOT EDIT!


#ifndef DIAG_MSGS_MESSAGE_VEHICLEAUTOFUNCTION_H
#define DIAG_MSGS_MESSAGE_VEHICLEAUTOFUNCTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diag_msgs
{
template <class ContainerAllocator>
struct VehicleAutoFunction_
{
  typedef VehicleAutoFunction_<ContainerAllocator> Type;

  VehicleAutoFunction_()
    : timestamp(0.0)
    , activation(0)  {
    }
  VehicleAutoFunction_(const ContainerAllocator& _alloc)
    : timestamp(0.0)
    , activation(0)  {
  (void)_alloc;
    }



   typedef double _timestamp_type;
  _timestamp_type timestamp;

   typedef int8_t _activation_type;
  _activation_type activation;





  typedef boost::shared_ptr< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleAutoFunction_

typedef ::diag_msgs::VehicleAutoFunction_<std::allocator<void> > VehicleAutoFunction;

typedef boost::shared_ptr< ::diag_msgs::VehicleAutoFunction > VehicleAutoFunctionPtr;
typedef boost::shared_ptr< ::diag_msgs::VehicleAutoFunction const> VehicleAutoFunctionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator1> & lhs, const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator2> & rhs)
{
  return lhs.timestamp == rhs.timestamp &&
    lhs.activation == rhs.activation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator1> & lhs, const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diag_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f89590bd8dcabcbb0b11733a25547518";
  }

  static const char* value(const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf89590bd8dcabcbbULL;
  static const uint64_t static_value2 = 0x0b11733a25547518ULL;
};

template<class ContainerAllocator>
struct DataType< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diag_msgs/VehicleAutoFunction";
  }

  static const char* value(const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 timestamp\n"
"int8 activation\n"
"\n"
;
  }

  static const char* value(const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.timestamp);
      stream.next(m.activation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleAutoFunction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diag_msgs::VehicleAutoFunction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diag_msgs::VehicleAutoFunction_<ContainerAllocator>& v)
  {
    s << indent << "timestamp: ";
    Printer<double>::stream(s, indent + "  ", v.timestamp);
    s << indent << "activation: ";
    Printer<int8_t>::stream(s, indent + "  ", v.activation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIAG_MSGS_MESSAGE_VEHICLEAUTOFUNCTION_H
