# v0.1
frame_id: base_link
map_data_path: /home/ydm/amr_ws/src/planning_rviz/config/path.csv

vehicle_interface:
#        length: 1.6
#        width: 0.8
#        height: 1.66
#        wheelbase: 0.8
#        front_overhang: 0.4
#        back_overhang: 0.4

# 1+x
        length: 4.41
        width: 1.8
        height: 1.66
        wheelbase: 2.62
        front_overhang: 1.0
        back_overhang: 0.814

# jinlong
#        length: 5.99
#        width: 2.06
#        height: 1.66
#        wheelbase: 4.0
#        front_overhang: 0.99
#        back_overhang: 0.99
# zk
#        length: 7.565
#        width: 2.55
#        height: 3.78
#        wheelbase: 3.92
#        front_overhang: 1.5
#        back_overhang: 0.865
#beiqi
#        length: 1.6
#        width: 1.2
#        height: 3.78
#        wheelbase: 1.0
#        front_overhang: 0.3
#        back_overhang: 0.3

vehicle_config:
    front_edge_to_center: 3.1
    back_edge_to_center: 0.5
    left_edge_to_center: 0.8
    right_edge_to_center: 0.8
    length: 3.6
    width: 1.6
    height: 2.8
    min_turn_radius: 4.0
    max_acceleration: 2.5
    max_deceleration: -5.0
    max_abs_speed_when_stopped: 0.1

    back_edge_to_center: 0.4
    left_edge_to_center: 0.4
    right_edge_to_center: 0.4
    length: 1.65
    width: 0.8
    height: 1.5
    min_turn_radius: 4.0
    max_acceleration: 2.5
    max_deceleration: -5.0
    max_abs_speed_when_stopped: 0.1


sub_topic_name:
        localization: cicv_location
        perception: tpperception
        trajectory: cicv_amr_trajectory
        reference: reference_trajectory
        routing_result: tprouteplan

pub_topic_name:
        localization: amr_pose
        perception: obstacle_display
        planning: trajectory_display
        reference: reference_display
        destination: destination_pose
        map: map_display


