(cl:defpackage control_msgs-msg
  (:use )
  (:export
   "<CONTROL_COMMAND>"
   "CONTROL_COMMAND"
   "<JINLONG_CONTROL_COMMAND>"
   "JINLONG_CONTROL_COMMAND"
   "<JINLONG_CONTROL_MODEFLAG>"
   "JINLONG_CONTROL_MODEFLAG"
  ))

