(cl:in-package common_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          STEER_AXLE_SPEED-VAL
          STEER_AXLE_SPEED
          REL_SPEED_STEER_AXLE_LEFT-VAL
          REL_SPEED_STEER_AXLE_LEFT
          REL_SPEED_STEER_AXLE_RIGHT-VAL
          REL_SPEED_STEER_AXLE_RIGHT
          REL_SPEED_REAR_AXLE_LEFT-VAL
          REL_SPEED_REAR_AXLE_LEFT
          REL_SPEED_REAR_AXLE_RIGHT-VAL
          REL_SPEED_REAR_AXLE_RIGHT
          STRG_ANGLE_REAL_VALUE-VAL
          STRG_ANGLE_REAL_VALUE
))