//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the dynamic package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __dynamic__DYNAMICCONFIG_H__
#define __dynamic__DYNAMICCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace dynamic
{
  class dynamicConfigStatics;

  class dynamicConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(dynamicConfig &config, const dynamicConfig &max, const dynamicConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const dynamicConfig &config1, const dynamicConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, dynamicConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const dynamicConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dynamicConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const dynamicConfig &config) const = 0;
      virtual void getValue(const dynamicConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T dynamicConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T dynamicConfig::* field;

      virtual void clamp(dynamicConfig &config, const dynamicConfig &max, const dynamicConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const dynamicConfig &config1, const dynamicConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, dynamicConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const dynamicConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, dynamicConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const dynamicConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const dynamicConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, dynamicConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, dynamicConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<dynamicConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(dynamicConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("AS_Strg_Angle_Req"==(*_i)->name){AS_Strg_Angle_Req = boost::any_cast<int>(val);}
        if("AS_Strg_WorkMode_Req"==(*_i)->name){AS_Strg_WorkMode_Req = boost::any_cast<int>(val);}
        if("AS_Strg0_Enable"==(*_i)->name){AS_Strg0_Enable = boost::any_cast<int>(val);}
        if("AS_Steering_torque_superposition"==(*_i)->name){AS_Steering_torque_superposition = boost::any_cast<int>(val);}
        if("AS_Strg_Spd_Req"==(*_i)->name){AS_Strg_Spd_Req = boost::any_cast<int>(val);}
        if("AS_Strg1_Enable"==(*_i)->name){AS_Strg1_Enable = boost::any_cast<int>(val);}
        if("AS_AutoD_Req"==(*_i)->name){AS_AutoD_Req = boost::any_cast<int>(val);}
        if("AS_Longit_Ctrlmode"==(*_i)->name){AS_Longit_Ctrlmode = boost::any_cast<int>(val);}
        if("AS_AutoD_EmergBrk_Release"==(*_i)->name){AS_AutoD_EmergBrk_Release = boost::any_cast<int>(val);}
        if("AS_AutoD_Collision_Release"==(*_i)->name){AS_AutoD_Collision_Release = boost::any_cast<int>(val);}
        if("AS_AutoD_Accel_Pos_Req"==(*_i)->name){AS_AutoD_Accel_Pos_Req = boost::any_cast<int>(val);}
        if("AS_AutoD_Shift_Req"==(*_i)->name){AS_AutoD_Shift_Req = boost::any_cast<int>(val);}
        if("AS_AutoD_P_Shift_Req"==(*_i)->name){AS_AutoD_P_Shift_Req = boost::any_cast<int>(val);}
        if("AS_AutoD_BrkMode_Req"==(*_i)->name){AS_AutoD_BrkMode_Req = boost::any_cast<int>(val);}
        if("AS_AutoD_BrkPelPos_Req"==(*_i)->name){AS_AutoD_BrkPelPos_Req = boost::any_cast<int>(val);}
        if("AS_AutoD_Spd_Limit"==(*_i)->name){AS_AutoD_Spd_Limit = boost::any_cast<int>(val);}
        if("AS_Auto_Acceleration_Req"==(*_i)->name){AS_Auto_Acceleration_Req = boost::any_cast<int>(val);}
        if("AS_AutoD_Spd_Req"==(*_i)->name){AS_AutoD_Spd_Req = boost::any_cast<int>(val);}
        if("AS_AlarmLamp_Req"==(*_i)->name){AS_AlarmLamp_Req = boost::any_cast<int>(val);}
        if("AS_Front_Door_Ctrl_Req"==(*_i)->name){AS_Front_Door_Ctrl_Req = boost::any_cast<int>(val);}
        if("AS_LowBeam_Start_Req"==(*_i)->name){AS_LowBeam_Start_Req = boost::any_cast<int>(val);}
        if("AS_TurnLeftLight_Start_Req"==(*_i)->name){AS_TurnLeftLight_Start_Req = boost::any_cast<int>(val);}
        if("AS_TurnRightLight_Start_Req"==(*_i)->name){AS_TurnRightLight_Start_Req = boost::any_cast<int>(val);}
        if("AS_MiniLight_Start_Req"==(*_i)->name){AS_MiniLight_Start_Req = boost::any_cast<int>(val);}
        if("AS_Horn_Start_Req"==(*_i)->name){AS_Horn_Start_Req = boost::any_cast<int>(val);}
        if("AS_Treadle_Operating_Req"==(*_i)->name){AS_Treadle_Operating_Req = boost::any_cast<int>(val);}
        if("AS_FDoorButtonLock_Req"==(*_i)->name){AS_FDoorButtonLock_Req = boost::any_cast<int>(val);}
        if("AS_Mid_Door_Ctrl_Req"==(*_i)->name){AS_Mid_Door_Ctrl_Req = boost::any_cast<int>(val);}
        if("AS_MDoorButtonLock_Req"==(*_i)->name){AS_MDoorButtonLock_Req = boost::any_cast<int>(val);}
        if("AS_Rear_Door_Ctrl_Req"==(*_i)->name){AS_Rear_Door_Ctrl_Req = boost::any_cast<int>(val);}
        if("AS_RDoorButtonLock_Req"==(*_i)->name){AS_RDoorButtonLock_Req = boost::any_cast<int>(val);}
        if("AS_FrontFog_Req"==(*_i)->name){AS_FrontFog_Req = boost::any_cast<int>(val);}
        if("AS_RearFog_Req"==(*_i)->name){AS_RearFog_Req = boost::any_cast<int>(val);}
        if("AS_Warninglight_Req"==(*_i)->name){AS_Warninglight_Req = boost::any_cast<int>(val);}
        if("AS_HighBeam_Start_Req"==(*_i)->name){AS_HighBeam_Start_Req = boost::any_cast<int>(val);}
      }
    }

    int AS_Strg_Angle_Req;
int AS_Strg_WorkMode_Req;
int AS_Strg0_Enable;
int AS_Steering_torque_superposition;
int AS_Strg_Spd_Req;
int AS_Strg1_Enable;
int AS_AutoD_Req;
int AS_Longit_Ctrlmode;
int AS_AutoD_EmergBrk_Release;
int AS_AutoD_Collision_Release;
int AS_AutoD_Accel_Pos_Req;
int AS_AutoD_Shift_Req;
int AS_AutoD_P_Shift_Req;
int AS_AutoD_BrkMode_Req;
int AS_AutoD_BrkPelPos_Req;
int AS_AutoD_Spd_Limit;
int AS_Auto_Acceleration_Req;
int AS_AutoD_Spd_Req;
int AS_AlarmLamp_Req;
int AS_Front_Door_Ctrl_Req;
int AS_LowBeam_Start_Req;
int AS_TurnLeftLight_Start_Req;
int AS_TurnRightLight_Start_Req;
int AS_MiniLight_Start_Req;
int AS_Horn_Start_Req;
int AS_Treadle_Operating_Req;
int AS_FDoorButtonLock_Req;
int AS_Mid_Door_Ctrl_Req;
int AS_MDoorButtonLock_Req;
int AS_Rear_Door_Ctrl_Req;
int AS_RDoorButtonLock_Req;
int AS_FrontFog_Req;
int AS_RearFog_Req;
int AS_Warninglight_Req;
int AS_HighBeam_Start_Req;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Strg_Angle_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Strg_WorkMode_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Strg0_Enable;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Steering_torque_superposition;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Strg_Spd_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Strg1_Enable;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Longit_Ctrlmode;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_EmergBrk_Release;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_Collision_Release;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_Accel_Pos_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_Shift_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_P_Shift_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_BrkMode_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_BrkPelPos_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_Spd_Limit;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Auto_Acceleration_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AutoD_Spd_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_AlarmLamp_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Front_Door_Ctrl_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_LowBeam_Start_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_TurnLeftLight_Start_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_TurnRightLight_Start_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_MiniLight_Start_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Horn_Start_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Treadle_Operating_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_FDoorButtonLock_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Mid_Door_Ctrl_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_MDoorButtonLock_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Rear_Door_Ctrl_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_RDoorButtonLock_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_FrontFog_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_RearFog_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_Warninglight_Req;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int AS_HighBeam_Start_Req;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("dynamicConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const dynamicConfig &__max__ = __getMax__();
      const dynamicConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const dynamicConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const dynamicConfig &__getDefault__();
    static const dynamicConfig &__getMax__();
    static const dynamicConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const dynamicConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void dynamicConfig::ParamDescription<std::string>::clamp(dynamicConfig &config, const dynamicConfig &max, const dynamicConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class dynamicConfigStatics
  {
    friend class dynamicConfig;

    dynamicConfigStatics()
    {
dynamicConfig::GroupDescription<dynamicConfig::DEFAULT, dynamicConfig> Default("Default", "", 0, 0, true, &dynamicConfig::groups);
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Strg_Angle_Req = -3000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Strg_Angle_Req = 3000;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Strg_Angle_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg_Angle_Req", "int", 0, "Strg_Angle_Req", "", &dynamicConfig::AS_Strg_Angle_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg_Angle_Req", "int", 0, "Strg_Angle_Req", "", &dynamicConfig::AS_Strg_Angle_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Strg_WorkMode_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Strg_WorkMode_Req = 6;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Strg_WorkMode_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg_WorkMode_Req", "int", 0, "Strg_WorkMode_Req", "{'enum': [{'name': 'reserve0', 'type': 'int', 'value': 0, 'srcline': 15, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserve0', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'auto', 'type': 'int', 'value': 1, 'srcline': 16, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'auto', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'reserve2', 'type': 'int', 'value': 2, 'srcline': 17, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserve2', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'm_s', 'type': 'int', 'value': 3, 'srcline': 18, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'm_s', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'human', 'type': 'int', 'value': 4, 'srcline': 19, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'human', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'human_resume', 'type': 'int', 'value': 5, 'srcline': 20, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'human_resume', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'clear_error', 'type': 'int', 'value': 6, 'srcline': 21, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'clear_error', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Strg'}", &dynamicConfig::AS_Strg_WorkMode_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg_WorkMode_Req", "int", 0, "Strg_WorkMode_Req", "{'enum': [{'name': 'reserve0', 'type': 'int', 'value': 0, 'srcline': 15, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserve0', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'auto', 'type': 'int', 'value': 1, 'srcline': 16, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'auto', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'reserve2', 'type': 'int', 'value': 2, 'srcline': 17, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserve2', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'm_s', 'type': 'int', 'value': 3, 'srcline': 18, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'm_s', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'human', 'type': 'int', 'value': 4, 'srcline': 19, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'human', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'human_resume', 'type': 'int', 'value': 5, 'srcline': 20, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'human_resume', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'clear_error', 'type': 'int', 'value': 6, 'srcline': 21, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'clear_error', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Strg'}", &dynamicConfig::AS_Strg_WorkMode_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Strg0_Enable = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Strg0_Enable = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Strg0_Enable = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg0_Enable", "int", 0, "AS_Strg0_Enable", "{'enum': [{'name': 'not_active0', 'type': 'int', 'value': 0, 'srcline': 24, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_active0', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid10', 'type': 'int', 'value': 1, 'srcline': 25, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid10', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid20', 'type': 'int', 'value': 2, 'srcline': 26, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid20', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'active0', 'type': 'int', 'value': 3, 'srcline': 27, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'active0', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'strg0_enable'}", &dynamicConfig::AS_Strg0_Enable)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg0_Enable", "int", 0, "AS_Strg0_Enable", "{'enum': [{'name': 'not_active0', 'type': 'int', 'value': 0, 'srcline': 24, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_active0', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid10', 'type': 'int', 'value': 1, 'srcline': 25, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid10', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid20', 'type': 'int', 'value': 2, 'srcline': 26, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid20', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'active0', 'type': 'int', 'value': 3, 'srcline': 27, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'active0', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'strg0_enable'}", &dynamicConfig::AS_Strg0_Enable)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Steering_torque_superposition = -13;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Steering_torque_superposition = 13;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Steering_torque_superposition = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Steering_torque_superposition", "int", 0, "AS_Steering_torque_superposition", "", &dynamicConfig::AS_Steering_torque_superposition)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Steering_torque_superposition", "int", 0, "AS_Steering_torque_superposition", "", &dynamicConfig::AS_Steering_torque_superposition)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Strg_Spd_Req = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Strg_Spd_Req = 540;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Strg_Spd_Req = 10;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg_Spd_Req", "int", 0, "AS_Strg_Spd_Req", "", &dynamicConfig::AS_Strg_Spd_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg_Spd_Req", "int", 0, "AS_Strg_Spd_Req", "", &dynamicConfig::AS_Strg_Spd_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Strg1_Enable = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Strg1_Enable = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Strg1_Enable = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg1_Enable", "int", 0, "AS_Strg1_Enable", "{'enum': [{'name': 'not_active1', 'type': 'int', 'value': 0, 'srcline': 32, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_active1', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid11', 'type': 'int', 'value': 1, 'srcline': 33, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid11', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid21', 'type': 'int', 'value': 2, 'srcline': 34, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid21', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'active1', 'type': 'int', 'value': 3, 'srcline': 35, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'active1', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'strg1_enable'}", &dynamicConfig::AS_Strg1_Enable)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Strg1_Enable", "int", 0, "AS_Strg1_Enable", "{'enum': [{'name': 'not_active1', 'type': 'int', 'value': 0, 'srcline': 32, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_active1', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid11', 'type': 'int', 'value': 1, 'srcline': 33, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid11', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid21', 'type': 'int', 'value': 2, 'srcline': 34, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid21', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'active1', 'type': 'int', 'value': 3, 'srcline': 35, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'active1', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'strg1_enable'}", &dynamicConfig::AS_Strg1_Enable)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_Req = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Req", "int", 0, "AS_AutoD_Req", "{'enum': [{'name': 'not_active', 'type': 'int', 'value': 0, 'srcline': 48, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_active', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'active', 'type': 'int', 'value': 1, 'srcline': 49, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'active', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'error', 'type': 'int', 'value': 2, 'srcline': 50, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'error', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid_autod_req', 'type': 'int', 'value': 3, 'srcline': 51, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_autod_req', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_Req'}", &dynamicConfig::AS_AutoD_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Req", "int", 0, "AS_AutoD_Req", "{'enum': [{'name': 'not_active', 'type': 'int', 'value': 0, 'srcline': 48, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_active', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'active', 'type': 'int', 'value': 1, 'srcline': 49, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'active', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'error', 'type': 'int', 'value': 2, 'srcline': 50, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'error', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid_autod_req', 'type': 'int', 'value': 3, 'srcline': 51, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_autod_req', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_Req'}", &dynamicConfig::AS_AutoD_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Longit_Ctrlmode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Longit_Ctrlmode = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Longit_Ctrlmode = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Longit_Ctrlmode", "int", 0, "AS_Longit_Ctrlmode_", "{'enum': [{'name': 'invalid_longit_ctrlmode', 'type': 'int', 'value': 0, 'srcline': 54, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_longit_ctrlmode', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'pedctrl', 'type': 'int', 'value': 1, 'srcline': 55, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'pedctrl', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'accelctrl', 'type': 'int', 'value': 2, 'srcline': 56, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'accelctrl', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'reserve', 'type': 'int', 'value': 3, 'srcline': 57, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserve', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Longit_Ctrlmode'}", &dynamicConfig::AS_Longit_Ctrlmode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Longit_Ctrlmode", "int", 0, "AS_Longit_Ctrlmode_", "{'enum': [{'name': 'invalid_longit_ctrlmode', 'type': 'int', 'value': 0, 'srcline': 54, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_longit_ctrlmode', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'pedctrl', 'type': 'int', 'value': 1, 'srcline': 55, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'pedctrl', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'accelctrl', 'type': 'int', 'value': 2, 'srcline': 56, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'accelctrl', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'reserve', 'type': 'int', 'value': 3, 'srcline': 57, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserve', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Longit_Ctrlmode'}", &dynamicConfig::AS_Longit_Ctrlmode)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_EmergBrk_Release = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_EmergBrk_Release = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_EmergBrk_Release = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_EmergBrk_Release", "int", 0, "AS_AutoD_EmergBrk_Release_", "", &dynamicConfig::AS_AutoD_EmergBrk_Release)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_EmergBrk_Release", "int", 0, "AS_AutoD_EmergBrk_Release_", "", &dynamicConfig::AS_AutoD_EmergBrk_Release)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_Collision_Release = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_Collision_Release = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_Collision_Release = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Collision_Release", "int", 0, "AS_AutoD_Collision_Release_", "{'enum': [{'name': 'not_release', 'type': 'int', 'value': 0, 'srcline': 61, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_release', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'front_release', 'type': 'int', 'value': 1, 'srcline': 62, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'front_release', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'rear_release', 'type': 'int', 'value': 2, 'srcline': 63, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'rear_release', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_Collision_Release'}", &dynamicConfig::AS_AutoD_Collision_Release)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Collision_Release", "int", 0, "AS_AutoD_Collision_Release_", "{'enum': [{'name': 'not_release', 'type': 'int', 'value': 0, 'srcline': 61, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_release', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'front_release', 'type': 'int', 'value': 1, 'srcline': 62, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'front_release', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'rear_release', 'type': 'int', 'value': 2, 'srcline': 63, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'rear_release', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_Collision_Release'}", &dynamicConfig::AS_AutoD_Collision_Release)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_Accel_Pos_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_Accel_Pos_Req = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_Accel_Pos_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Accel_Pos_Req", "int", 0, "AS_AutoD_Accel_Pos_Req_", "", &dynamicConfig::AS_AutoD_Accel_Pos_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Accel_Pos_Req", "int", 0, "AS_AutoD_Accel_Pos_Req_", "", &dynamicConfig::AS_AutoD_Accel_Pos_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_Shift_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_Shift_Req = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_Shift_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Shift_Req", "int", 0, "AS_AutoD_Shift_Req_", "{'enum': [{'name': 'invalid_gear', 'type': 'int', 'value': 0, 'srcline': 67, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_gear', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gear_R', 'type': 'int', 'value': 1, 'srcline': 68, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'gear_R', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gear_N', 'type': 'int', 'value': 2, 'srcline': 69, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'gear_N', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gear_D', 'type': 'int', 'value': 3, 'srcline': 70, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'gear_D', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_Shift_Req'}", &dynamicConfig::AS_AutoD_Shift_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Shift_Req", "int", 0, "AS_AutoD_Shift_Req_", "{'enum': [{'name': 'invalid_gear', 'type': 'int', 'value': 0, 'srcline': 67, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_gear', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gear_R', 'type': 'int', 'value': 1, 'srcline': 68, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'gear_R', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gear_N', 'type': 'int', 'value': 2, 'srcline': 69, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'gear_N', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gear_D', 'type': 'int', 'value': 3, 'srcline': 70, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'gear_D', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_Shift_Req'}", &dynamicConfig::AS_AutoD_Shift_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_P_Shift_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_P_Shift_Req = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_P_Shift_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_P_Shift_Req", "int", 0, "AS_AutoD_P_Shift_Req_", "{'enum': [{'name': 'invalid_p_gear', 'type': 'int', 'value': 0, 'srcline': 73, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_p_gear', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'release_p', 'type': 'int', 'value': 1, 'srcline': 74, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'release_p', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'p', 'type': 'int', 'value': 2, 'srcline': 75, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'p', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_P_Shift_Req'}", &dynamicConfig::AS_AutoD_P_Shift_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_P_Shift_Req", "int", 0, "AS_AutoD_P_Shift_Req_", "{'enum': [{'name': 'invalid_p_gear', 'type': 'int', 'value': 0, 'srcline': 73, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_p_gear', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'release_p', 'type': 'int', 'value': 1, 'srcline': 74, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'release_p', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'p', 'type': 'int', 'value': 2, 'srcline': 75, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'p', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_P_Shift_Req'}", &dynamicConfig::AS_AutoD_P_Shift_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_BrkMode_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_BrkMode_Req = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_BrkMode_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_BrkMode_Req", "int", 0, "AS_AutoD_BrkMode_Req_", "{'enum': [{'name': 'major_brk', 'type': 'int', 'value': 0, 'srcline': 78, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'major_brk', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'reserved_brk', 'type': 'int', 'value': 1, 'srcline': 79, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserved_brk', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid_brkmode', 'type': 'int', 'value': 2, 'srcline': 80, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_brkmode', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'major_reserved', 'type': 'int', 'value': 3, 'srcline': 81, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'major_reserved', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_BrkMode_Req'}", &dynamicConfig::AS_AutoD_BrkMode_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_BrkMode_Req", "int", 0, "AS_AutoD_BrkMode_Req_", "{'enum': [{'name': 'major_brk', 'type': 'int', 'value': 0, 'srcline': 78, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'major_brk', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'reserved_brk', 'type': 'int', 'value': 1, 'srcline': 79, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'reserved_brk', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'invalid_brkmode', 'type': 'int', 'value': 2, 'srcline': 80, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'invalid_brkmode', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'major_reserved', 'type': 'int', 'value': 3, 'srcline': 81, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'major_reserved', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'AutoD_BrkMode_Req'}", &dynamicConfig::AS_AutoD_BrkMode_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_BrkPelPos_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_BrkPelPos_Req = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_BrkPelPos_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_BrkPelPos_Req", "int", 0, "AS_AutoD_BrkPelPos_Req_", "", &dynamicConfig::AS_AutoD_BrkPelPos_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_BrkPelPos_Req", "int", 0, "AS_AutoD_BrkPelPos_Req_", "", &dynamicConfig::AS_AutoD_BrkPelPos_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_Spd_Limit = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_Spd_Limit = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_Spd_Limit = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Spd_Limit", "int", 0, "AS_AutoD_Spd_Limit_", "", &dynamicConfig::AS_AutoD_Spd_Limit)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Spd_Limit", "int", 0, "AS_AutoD_Spd_Limit_", "", &dynamicConfig::AS_AutoD_Spd_Limit)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Auto_Acceleration_Req = -15;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Auto_Acceleration_Req = 15;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Auto_Acceleration_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Auto_Acceleration_Req", "int", 0, "AS_Auto_Acceleration_Req_", "", &dynamicConfig::AS_Auto_Acceleration_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Auto_Acceleration_Req", "int", 0, "AS_Auto_Acceleration_Req_", "", &dynamicConfig::AS_Auto_Acceleration_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AutoD_Spd_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AutoD_Spd_Req = 100;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AutoD_Spd_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Spd_Req", "int", 0, "AS_AutoD_Spd_Req_", "", &dynamicConfig::AS_AutoD_Spd_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AutoD_Spd_Req", "int", 0, "AS_AutoD_Spd_Req_", "", &dynamicConfig::AS_AutoD_Spd_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_AlarmLamp_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_AlarmLamp_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_AlarmLamp_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AlarmLamp_Req", "int", 0, "AS_AlarmLamp_Req_", "", &dynamicConfig::AS_AlarmLamp_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_AlarmLamp_Req", "int", 0, "AS_AlarmLamp_Req_", "", &dynamicConfig::AS_AlarmLamp_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Front_Door_Ctrl_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Front_Door_Ctrl_Req = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Front_Door_Ctrl_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Front_Door_Ctrl_Req", "int", 0, "AS_Front_Door_Ctrl_Req_", "{'enum': [{'name': 'not_operating', 'type': 'int', 'value': 0, 'srcline': 107, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_door', 'type': 'int', 'value': 1, 'srcline': 108, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'close_door', 'type': 'int', 'value': 2, 'srcline': 109, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'close_door', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Front_Door_Ctrl_Req'}", &dynamicConfig::AS_Front_Door_Ctrl_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Front_Door_Ctrl_Req", "int", 0, "AS_Front_Door_Ctrl_Req_", "{'enum': [{'name': 'not_operating', 'type': 'int', 'value': 0, 'srcline': 107, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_door', 'type': 'int', 'value': 1, 'srcline': 108, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'close_door', 'type': 'int', 'value': 2, 'srcline': 109, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'close_door', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Front_Door_Ctrl_Req'}", &dynamicConfig::AS_Front_Door_Ctrl_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_LowBeam_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_LowBeam_Start_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_LowBeam_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_LowBeam_Start_Req", "int", 0, "AS_LowBeam_Start_Req_", "", &dynamicConfig::AS_LowBeam_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_LowBeam_Start_Req", "int", 0, "AS_LowBeam_Start_Req_", "", &dynamicConfig::AS_LowBeam_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_TurnLeftLight_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_TurnLeftLight_Start_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_TurnLeftLight_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_TurnLeftLight_Start_Req", "int", 0, "AS_TurnLeftLight_Start_Req_", "", &dynamicConfig::AS_TurnLeftLight_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_TurnLeftLight_Start_Req", "int", 0, "AS_TurnLeftLight_Start_Req_", "", &dynamicConfig::AS_TurnLeftLight_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_TurnRightLight_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_TurnRightLight_Start_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_TurnRightLight_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_TurnRightLight_Start_Req", "int", 0, "AS_TurnRightLight_Start_Req_", "", &dynamicConfig::AS_TurnRightLight_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_TurnRightLight_Start_Req", "int", 0, "AS_TurnRightLight_Start_Req_", "", &dynamicConfig::AS_TurnRightLight_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_MiniLight_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_MiniLight_Start_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_MiniLight_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_MiniLight_Start_Req", "int", 0, "AS_MiniLight_Start_Req_", "", &dynamicConfig::AS_MiniLight_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_MiniLight_Start_Req", "int", 0, "AS_MiniLight_Start_Req_", "", &dynamicConfig::AS_MiniLight_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Horn_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Horn_Start_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Horn_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Horn_Start_Req", "int", 0, "AS_Horn_Start_Req_", "", &dynamicConfig::AS_Horn_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Horn_Start_Req", "int", 0, "AS_Horn_Start_Req_", "", &dynamicConfig::AS_Horn_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Treadle_Operating_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Treadle_Operating_Req = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Treadle_Operating_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Treadle_Operating_Req", "int", 0, "AS_Treadle_Operating_Req_", "{'enum': [{'name': 'not_operating_treadle', 'type': 'int', 'value': 0, 'srcline': 117, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating_treadle', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'run_out', 'type': 'int', 'value': 1, 'srcline': 118, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'run_out', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'take_back', 'type': 'int', 'value': 2, 'srcline': 119, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'take_back', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Treadle_Operating_Req'}", &dynamicConfig::AS_Treadle_Operating_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Treadle_Operating_Req", "int", 0, "AS_Treadle_Operating_Req_", "{'enum': [{'name': 'not_operating_treadle', 'type': 'int', 'value': 0, 'srcline': 117, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating_treadle', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'run_out', 'type': 'int', 'value': 1, 'srcline': 118, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'run_out', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'take_back', 'type': 'int', 'value': 2, 'srcline': 119, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'take_back', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Treadle_Operating_Req'}", &dynamicConfig::AS_Treadle_Operating_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_FDoorButtonLock_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_FDoorButtonLock_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_FDoorButtonLock_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_FDoorButtonLock_Req", "int", 0, "AS_FDoorButtonLock_Req_", "", &dynamicConfig::AS_FDoorButtonLock_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_FDoorButtonLock_Req", "int", 0, "AS_FDoorButtonLock_Req_", "", &dynamicConfig::AS_FDoorButtonLock_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Mid_Door_Ctrl_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Mid_Door_Ctrl_Req = 2;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Mid_Door_Ctrl_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Mid_Door_Ctrl_Req", "int", 0, "AS_Mid_Door_Ctrl_Req_", "{'enum': [{'name': 'not_operating_mid_door', 'type': 'int', 'value': 0, 'srcline': 123, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating_mid_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_mid_door', 'type': 'int', 'value': 1, 'srcline': 124, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_mid_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'close_mid_door', 'type': 'int', 'value': 2, 'srcline': 125, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'close_mid_door', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Mid_Door_Ctrl_Req'}", &dynamicConfig::AS_Mid_Door_Ctrl_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Mid_Door_Ctrl_Req", "int", 0, "AS_Mid_Door_Ctrl_Req_", "{'enum': [{'name': 'not_operating_mid_door', 'type': 'int', 'value': 0, 'srcline': 123, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating_mid_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_mid_door', 'type': 'int', 'value': 1, 'srcline': 124, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_mid_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'close_mid_door', 'type': 'int', 'value': 2, 'srcline': 125, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'close_mid_door', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Mid_Door_Ctrl_Req'}", &dynamicConfig::AS_Mid_Door_Ctrl_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_MDoorButtonLock_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_MDoorButtonLock_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_MDoorButtonLock_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_MDoorButtonLock_Req", "int", 0, "AS_MDoorButtonLock_Req_", "", &dynamicConfig::AS_MDoorButtonLock_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_MDoorButtonLock_Req", "int", 0, "AS_MDoorButtonLock_Req_", "", &dynamicConfig::AS_MDoorButtonLock_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Rear_Door_Ctrl_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Rear_Door_Ctrl_Req = 3;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Rear_Door_Ctrl_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Rear_Door_Ctrl_Req", "int", 0, "AS_Rear_Door_Ctrl_Req_", "{'enum': [{'name': 'not_operating_rear_door', 'type': 'int', 'value': 0, 'srcline': 129, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_rear_door', 'type': 'int', 'value': 1, 'srcline': 130, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'close_rear_door', 'type': 'int', 'value': 2, 'srcline': 131, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'close_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_half_rear_door', 'type': 'int', 'value': 3, 'srcline': 132, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_half_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rear_Door_Ctrl_Req'}", &dynamicConfig::AS_Rear_Door_Ctrl_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Rear_Door_Ctrl_Req", "int", 0, "AS_Rear_Door_Ctrl_Req_", "{'enum': [{'name': 'not_operating_rear_door', 'type': 'int', 'value': 0, 'srcline': 129, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'not_operating_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_rear_door', 'type': 'int', 'value': 1, 'srcline': 130, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'close_rear_door', 'type': 'int', 'value': 2, 'srcline': 131, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'close_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'open_half_rear_door', 'type': 'int', 'value': 3, 'srcline': 132, 'srcfile': '/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg', 'description': 'open_half_rear_door', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'Rear_Door_Ctrl_Req'}", &dynamicConfig::AS_Rear_Door_Ctrl_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_RDoorButtonLock_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_RDoorButtonLock_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_RDoorButtonLock_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_RDoorButtonLock_Req", "int", 0, "AS_RDoorButtonLock_Req_", "", &dynamicConfig::AS_RDoorButtonLock_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_RDoorButtonLock_Req", "int", 0, "AS_RDoorButtonLock_Req_", "", &dynamicConfig::AS_RDoorButtonLock_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_FrontFog_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_FrontFog_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_FrontFog_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_FrontFog_Req", "int", 0, "AS_FrontFog_Req_", "", &dynamicConfig::AS_FrontFog_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_FrontFog_Req", "int", 0, "AS_FrontFog_Req_", "", &dynamicConfig::AS_FrontFog_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_RearFog_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_RearFog_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_RearFog_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_RearFog_Req", "int", 0, "AS_RearFog_Req_", "", &dynamicConfig::AS_RearFog_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_RearFog_Req", "int", 0, "AS_RearFog_Req_", "", &dynamicConfig::AS_RearFog_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_Warninglight_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_Warninglight_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_Warninglight_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Warninglight_Req", "int", 0, "AS_Warninglight_Req_", "", &dynamicConfig::AS_Warninglight_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_Warninglight_Req", "int", 0, "AS_Warninglight_Req_", "", &dynamicConfig::AS_Warninglight_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.AS_HighBeam_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.AS_HighBeam_Start_Req = 1;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.AS_HighBeam_Start_Req = 0;
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_HighBeam_Start_Req", "int", 0, "AS_HighBeam_Start_Req_", "", &dynamicConfig::AS_HighBeam_Start_Req)));
//#line 291 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(dynamicConfig::AbstractParamDescriptionConstPtr(new dynamicConfig::ParamDescription<int>("AS_HighBeam_Start_Req", "int", 0, "AS_HighBeam_Start_Req_", "", &dynamicConfig::AS_HighBeam_Start_Req)));
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(dynamicConfig::AbstractGroupDescriptionConstPtr(new dynamicConfig::GroupDescription<dynamicConfig::DEFAULT, dynamicConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<dynamicConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<dynamicConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<dynamicConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    dynamicConfig __max__;
    dynamicConfig __min__;
    dynamicConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const dynamicConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static dynamicConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &dynamicConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const dynamicConfig &dynamicConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const dynamicConfig &dynamicConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const dynamicConfig &dynamicConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<dynamicConfig::AbstractParamDescriptionConstPtr> &dynamicConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<dynamicConfig::AbstractGroupDescriptionConstPtr> &dynamicConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const dynamicConfigStatics *dynamicConfig::__get_statics__()
  {
    const static dynamicConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = dynamicConfigStatics::get_instance();

    return statics;
  }

//#line 15 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_reserve0 = 0;
//#line 16 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_auto = 1;
//#line 17 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_reserve2 = 2;
//#line 18 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_m_s = 3;
//#line 19 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_human = 4;
//#line 20 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_human_resume = 5;
//#line 21 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_clear_error = 6;
//#line 24 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_active0 = 0;
//#line 25 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid10 = 1;
//#line 26 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid20 = 2;
//#line 27 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_active0 = 3;
//#line 32 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_active1 = 0;
//#line 33 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid11 = 1;
//#line 34 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid21 = 2;
//#line 35 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_active1 = 3;
//#line 48 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_active = 0;
//#line 49 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_active = 1;
//#line 50 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_error = 2;
//#line 51 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid_autod_req = 3;
//#line 54 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid_longit_ctrlmode = 0;
//#line 55 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_pedctrl = 1;
//#line 56 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_accelctrl = 2;
//#line 57 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_reserve = 3;
//#line 61 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_release = 0;
//#line 62 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_front_release = 1;
//#line 63 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_rear_release = 2;
//#line 67 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid_gear = 0;
//#line 68 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_gear_R = 1;
//#line 69 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_gear_N = 2;
//#line 70 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_gear_D = 3;
//#line 73 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid_p_gear = 0;
//#line 74 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_release_p = 1;
//#line 75 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_p = 2;
//#line 78 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_major_brk = 0;
//#line 79 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_reserved_brk = 1;
//#line 80 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_invalid_brkmode = 2;
//#line 81 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_major_reserved = 3;
//#line 107 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_operating = 0;
//#line 108 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_open_door = 1;
//#line 109 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_close_door = 2;
//#line 117 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_operating_treadle = 0;
//#line 118 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_run_out = 1;
//#line 119 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_take_back = 2;
//#line 123 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_operating_mid_door = 0;
//#line 124 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_open_mid_door = 1;
//#line 125 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_close_mid_door = 2;
//#line 129 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_not_operating_rear_door = 0;
//#line 130 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_open_rear_door = 1;
//#line 131 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_close_rear_door = 2;
//#line 132 "/home/server/2024ac/catkin_board/src/control/cfg/dynamic.cfg"
      const int dynamic_open_half_rear_door = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DYNAMICRECONFIGURATOR_H__
