// Generated by gencpp from file vehicle_msgs/VehicleSystem.msg
// DO NOT EDIT!


#ifndef VEHICLE_MSGS_MESSAGE_VEHICLESYSTEM_H
#define VEHICLE_MSGS_MESSAGE_VEHICLESYSTEM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <vehicle_msgs/SteeringSystem.h>

namespace vehicle_msgs
{
template <class ContainerAllocator>
struct VehicleSystem_
{
  typedef VehicleSystem_<ContainerAllocator> Type;

  VehicleSystem_()
    : header()
    , steering_system_info()  {
    }
  VehicleSystem_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steering_system_info(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::vehicle_msgs::SteeringSystem_<ContainerAllocator>  _steering_system_info_type;
  _steering_system_info_type steering_system_info;





  typedef boost::shared_ptr< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSystem_

typedef ::vehicle_msgs::VehicleSystem_<std::allocator<void> > VehicleSystem;

typedef boost::shared_ptr< ::vehicle_msgs::VehicleSystem > VehicleSystemPtr;
typedef boost::shared_ptr< ::vehicle_msgs::VehicleSystem const> VehicleSystemConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vehicle_msgs::VehicleSystem_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vehicle_msgs::VehicleSystem_<ContainerAllocator1> & lhs, const ::vehicle_msgs::VehicleSystem_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steering_system_info == rhs.steering_system_info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vehicle_msgs::VehicleSystem_<ContainerAllocator1> & lhs, const ::vehicle_msgs::VehicleSystem_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vehicle_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1b80a47314ce012d2792335cb08b9d7";
  }

  static const char* value(const ::vehicle_msgs::VehicleSystem_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1b80a47314ce012ULL;
  static const uint64_t static_value2 = 0xd2792335cb08b9d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vehicle_msgs/VehicleSystem";
  }

  static const char* value(const ::vehicle_msgs::VehicleSystem_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"SteeringSystem steering_system_info\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: vehicle_msgs/SteeringSystem\n"
"int32 frame_id\n"
"bool left_lever_status  # 0 -- off; 1 -- on\n"
"bool right_lever_status # 0 -- off; 1 -- on\n"
"\n"
;
  }

  static const char* value(const ::vehicle_msgs::VehicleSystem_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steering_system_info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSystem_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vehicle_msgs::VehicleSystem_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vehicle_msgs::VehicleSystem_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steering_system_info: ";
    s << std::endl;
    Printer< ::vehicle_msgs::SteeringSystem_<ContainerAllocator> >::stream(s, indent + "  ", v.steering_system_info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VEHICLE_MSGS_MESSAGE_VEHICLESYSTEM_H
