# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vehicle_msgs/SteeringSystem.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SteeringSystem(genpy.Message):
  _md5sum = "767b136d6aedb502751d3e4cb984f813"
  _type = "vehicle_msgs/SteeringSystem"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 frame_id
bool left_lever_status  # 0 -- off; 1 -- on
bool right_lever_status # 0 -- off; 1 -- on

"""
  __slots__ = ['frame_id','left_lever_status','right_lever_status']
  _slot_types = ['int32','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       frame_id,left_lever_status,right_lever_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SteeringSystem, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.frame_id is None:
        self.frame_id = 0
      if self.left_lever_status is None:
        self.left_lever_status = False
      if self.right_lever_status is None:
        self.right_lever_status = False
    else:
      self.frame_id = 0
      self.left_lever_status = False
      self.right_lever_status = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2B().pack(_x.frame_id, _x.left_lever_status, _x.right_lever_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.frame_id, _x.left_lever_status, _x.right_lever_status,) = _get_struct_i2B().unpack(str[start:end])
      self.left_lever_status = bool(self.left_lever_status)
      self.right_lever_status = bool(self.right_lever_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2B().pack(_x.frame_id, _x.left_lever_status, _x.right_lever_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.frame_id, _x.left_lever_status, _x.right_lever_status,) = _get_struct_i2B().unpack(str[start:end])
      self.left_lever_status = bool(self.left_lever_status)
      self.right_lever_status = bool(self.right_lever_status)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2B = None
def _get_struct_i2B():
    global _struct_i2B
    if _struct_i2B is None:
        _struct_i2B = struct.Struct("<i2B")
    return _struct_i2B
